### ISSUE TITLE
Sample Datafile missing

### ISSUE THREAD

**Issue by WillianBR** [r2123b/tkinter-ttk-Treeview-Simple-Demo#2]
There is a line with the content:

`dataFileDir = "/Users/alumi/PycharmProjects/StocksInfoRetrieval/Data/data_mm.pkl"`

But the file is missing into the REPO.  It'll crash if run.

```
$ python ComplexTreeview.py
Traceback (most recent call last):
  File "ComplexTreeview.py", line 177, in <module>
    myTableViewer = TableViewer(_rootWindow, "Table View")
  File "ComplexTreeview.py", line 27, in __init__
    self.arrangeLeftFrameUI()
  File "ComplexTreeview.py", line 91, in arrangeLeftFrameUI
    self.showAllData()
  File "ComplexTreeview.py", line 110, in showAllData
    for i in range(0, self.tableData['HIGH'].size):
AttributeError: 'TableViewer' object has no attribute 'tableData'

```

**Comment by r2123b** [comment]
Hi @WillianBR ,

Thank you for your feedback. I've updated my code and uploaded a sample `.csv` file. If you still have some issue about my code, don't hesitate to create a new issue :)
